### ISSUE TITLE
Inconsistency with verification data

### ISSUE THREAD

**Issue by hannespetur** [FRED-2/OptiType#11]
Hey guys.

I'm developing geneotyper with a similar purpose as OptiType. When I was comparing it to OptiType I noticed there are some inconsistencies with the verification data I found on the 1000 Genomes FTP site ( ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/working/20140725_hla_genotypes/20140702_hla_diversity.txt ) and the data you use in your supplementary table S2.

For example: In your table you have...
* A*02:07 but 1000 genomes have 02:01 for samples NA18537, NA18550, NA18552, NA18573, NA18943, NA18966, NA18987, and NA19007.
* B*27:05 but 1000 genomes have 27:03/27:52/27:09 for sample NA12005.
* C*02:10 but 1000 genomes have 02:02 for samples NA18504, NA18505, NA18507, NA18522, and NA18870.

What's the reason behind this inconsistency? I'm sorry if you mention it somewhere in your article, but I couldn't find it.

Cheers,
Hannes

**Comment by b-schubert** [comment]
Hi Hannes,

The typings we used are the ones reported by Erlich et al. (Erlich,R.L. et al. (2011) Next-generation sequencing for HLA typing of class I loci. BMC Genomics, 12, 42.). These were the only available typings at the time of OptiType's development and the 'golden standard' for many other approaches.

The typings you are referring to are much newer (Gourraud, Pierre-Antoine, et al. "HLA diversity in the 1000 genomes dataset." (2014): e97282.) and were produced with a different technique. 

When comparing the different methods, you have to be careful which run-IDs were used to obtain the predicted typing.

Hope that clears up the confusion.

Best,
Benni

**Comment by hannespetur** [comment]
Ok, thanks for the fast response. It cleared up the confusion, although now I'm just really surprised by the number of difference in those two datasets.

Thanks,
Hannes
