### ISSUE TITLE
AttributeError: 'IndexedVarWithDomain' object has no attribute 'reset'

### ISSUE THREAD

**Issue by 6C3C41** [FRED-2/OptiType#13]
Hello,

I received the above error running on example data. Do you have any advice about how I can proceed? Thanks!

Command:
python OptiTypePipeline.py -i test/exome/NA11995_SRR766010_1_fished.fastq --verbose --dna --outdir /home/ubuntu/OptiType-master

Config:
[MAPPING]
#please specify the razerS3 binary path
RAZERS3=/usr/bin/razers3
THREADS=4

[LIBRARIES]
RNA_REF=/home/ubuntu/OptiType-master/data/hla_reference_rna.fasta
DNA_REF=/home/ubuntu/OptiType-master/data/hla_reference_dna.fasta
ALLELES=/home/ubuntu/OptiType-master/data/alleles.h5

[OPTIMIZATION]
#the solver has to be supported by Coopr
SOLVER=cbc
THREADS=1

Log:
0:00:00.33 Mapping NA11995_SRR766010_1_fished.fastq to GEN reference...
0:00:15.47 Generating binary hit matrix.
0:00:15.47 Loading alleles and read IDs from /home/ubuntu/OptiType-master/2015_09_27_22_16_19/2015_09_27_22_16_19_0.sam...
0:00:16.37 11179 alleles and 1909 reads found.
0:00:16.37 Initializing mapping matrix...
0:00:16.38 1909x11179 mapping matrix initialized. Populating 1344422 hits from SAM file...
        10% completed
        20% completed
        30% completed
        40% completed
        50% completed
        60% completed
        70% completed
        80% completed
        90% completed
        100% completed
0:03:20.32 1344422 elements filled. Matrix sparsity: 1 in 15.87

0:03:22.42 temporary pruning of identical rows and columns

0:03:22.51 Size of mtx with unique rows and columns: (434, 1021)
0:03:22.51 determining minimal set of non-overshadowed alleles
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/util/decorators.py:13: FutureWarning: diff is deprecated. Use difference instead
  FutureWarning)

0:03:23.70 Keeping only the minimal number of required alleles (125,)

0:03:23.70 Creating compact model...

0:03:23.83 Initializing OptiType model...
Traceback (most recent call last):
  File "OptiTypePipeline.py", line 322, in <module>
    result = op.solve(args.enumerate)
  File "/home/ubuntu/OptiType-master/model.py", line 142, in solve
    self.__instance.x.reset()
AttributeError: 'IndexedVarWithDomain' object has no attribute 'reset'`

**Comment by andras86** [comment]
Hi! This is due to Pyomo breaking compatibility in its most recent version. I suggest you downgrade to Pyomo 4.1.10527 for an immediate fix.

**Comment by 6C3C41** [comment]
Thank you, this solved the issue.
