### ISSUE TITLE
Hi dear @andras86 , What's the meanning for "introns from " as  picture beblow?  I found it apprearing in https://github.com/FRED-2/OptiType/blob/master/hlatyper.py

### ISSUE THREAD

**Issue by whiffen-cann** [FRED-2/OptiType#133]
![1667604278336](https://user-images.githubusercontent.com/12433724/200088616-d0c9792c-84d9-4d6f-ab5d-03477561df5d.png)

**Comment by b-schubert** [comment]
this indicates that the intro was imputed from the next closeted HLA with intronic information.
