### ISSUE TITLE
Does OptiType only predict alleles in "freq_alleles"

### ISSUE THREAD

**Issue by mourisl** [FRED-2/OptiType#134]
Thank you for developing this super accurate HLA genotyper. I was going through the code, and found that the results seemed to be filtered by the alleles series listed in freq_alleles (https://github.com/FRED-2/OptiType/blob/07c49bf6fc93e8846e8826df63100a0b069cbe40/OptiTypePipeline.py#L136, https://github.com/FRED-2/OptiType/blob/master/OptiTypePipeline.py#L366)? Is it the case? Thank you.

**Comment by b-schubert** [comment]
yes
