### ISSUE TITLE
Is it based on hg38 genome?

### ISSUE THREAD

**Issue by xiasijian** [FRED-2/OptiType#135]
![image](https://user-images.githubusercontent.com/39158528/225836881-329f5aea-0a1d-4473-ab51-922fbcef4ff9.png)
Thanks for your excellent software, I want to know whether these software is based on hg38 genome.

**Comment by edceeyuchen** [comment]
Same problem！If you have the answer？

**Comment by kiranfranklin999** [comment]
Same doubt! Could anyone confirm this? 
I'm using bam files aligned to hg38 and wanted to know whether this software is compatible with hg38 genome. 

Thank you!

**Comment by b-schubert** [comment]
No, it uses a custom reference of all known HLA sequences. But you can use your alignments to prefilter for reads falling into the HLA superlocus, which will speed up optitype‘s inference.

**Comment by kiranfranklin999** [comment]
@b-schubert Thank you for confirming. 

I'm trying to use the Optitype for my sample file. Like you said I'm filtering the reads for MHC complex regions [hg38 chr6:28,510,120-33,480,577] using samtools view and converting the bam2fq and passing the fastq files as i/p for optitype. On executing Optitype command, it generates intermediate bam file for 1st fastq file within couple of seconds but for 2nd fastq file it takes forever and it doesn't throw any logs or output. 

Could you help me to solve this?

![image](https://github.com/FRED-2/OptiType/assets/47182702/ed2f6f71-33ff-4256-847a-5f1a0f874898)
