### ISSUE TITLE
HLA class II prediction

### ISSUE THREAD

**Issue by alejandro-jimenezsanchez** [FRED-2/OptiType#16]
Hello again,

The OptiType paper says that "[OptiType] can be easily adapted to predict genotypes for loci other than HLA-I such as HLA-II". I was wondering if it's just a matter of changing some parameters in OptiTypePipeline.py or is something different. In any case, I am very interested in predicting HLA class II, so I was wondering how achievable this would be.

Best,
Alejandro

**Comment by alvinwt** [comment]
Hi, 
I have managed to install and run Optitype perfectly and I am wondering if there is a way to include HLA-II alleles. I would be really interested in the feature and I would like to know how to do it. I like how fast optitype runs and kudos to that.
