### ISSUE TITLE
"ValueError: cannot reindex from a duplicate axis"

### ISSUE THREAD

**Issue by 6C3C41** [FRED-2/OptiType#18]
Hello,

I received the following error. I am not familiar with python so am unable to investigate further. I have run OptiType successfully on many other similar files and encountered this error only once. Thank you in advance for your consideration.

Traceback (most recent call last):
  File "/home/ubuntu/OptiType-master/OptiTypePipeline.py", line 342, in <module>
    coverage_mat = ht.calculate_coverage(plot_variables, features, hlatype, features_used)
  File "/home/ubuntu/OptiType-master/hlatyper.py", line 505, in calculate_coverage
    hit_counts[reads]):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/series.py", line 561, in __getitem__
    return self._get_with(key)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/series.py", line 604, in _get_with
    return self.reindex(key)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/series.py", line 2151, in reindex
    return super(Series, self).reindex(index=index, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 1773, in reindex
    method, fill_value, copy).__finalize__(self)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 1790, in _reindex_axes
    fill_value=fill_value, copy=copy, allow_dups=False)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 1876, in _reindex_with_indexers
    copy=copy)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/internals.py", line 3150, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/index.py", line 1860, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis

System information:

Linux version 3.19.0-31-generic (buildd@lcy01-07) (gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13) ) #36-Ubuntu SMP Wed Oct 7 15:04:02 UTC 2015

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:        15.04
Codename:       vivid

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               1220.812
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4862.53
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-9,20-29
NUMA node1 CPU(s):     10-19,30-39

MemTotal:       165051848 kB
MemFree:         7424336 kB
MemAvailable:   111855276 kB
Buffers:          111620 kB
Cached:         102348516 kB
SwapCached:         9496 kB
Active:         91282240 kB
Inactive:       63390396 kB
Active(anon):   51573908 kB
Inactive(anon):   640368 kB
Active(file):   39708332 kB
Inactive(file): 62750028 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       1048572 kB
SwapFree:         766880 kB
Dirty:            120940 kB
Writeback:             0 kB
AnonPages:      52205360 kB
Mapped:            84072 kB
Shmem:               428 kB
Slab:            2388540 kB
SReclaimable:    2310464 kB
SUnreclaim:        78076 kB
KernelStack:       11584 kB
PageTables:       111768 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    83574496 kB
Committed_AS:   77935112 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      439564 kB
VmallocChunk:   34274108676 kB
HardwareCorrupted:     0 kB
AnonHugePages:  17944576 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      133116 kB
DirectMap2M:    167770112 kB

siblings        : 20
core id         : 8
cpu cores       : 10
apicid          : 49
initial apicid  : 49
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq monitor est ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm ida fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
bugs            :
bogomips        : 4862.53
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

**Comment by andras86** [comment]
Hi! I think I'll have to look into the data itself to tell. Could you send over the fished fastq files to me via Dropbox or similar? The intermediate bam files would do as well, if you've enabled that setting.

**Comment by 6C3C41** [comment]
I’m using raw fq input - ok if I send that or should I filter? Perhaps I will see if I can reproduce the error with a filtered file, and send?

Thanks a lot for your reply

**Comment by andras86** [comment]
I say let's do the filtering first with the command in the Readme and that smaller fastq will be enough to send. You could also attach your config file.

**Comment by 6C3C41** [comment]
I reinstalled the python reqs and can no longer reproduce this error, sorry. Thanks so much for your willingness to investigate!
