### ISSUE TITLE
Solver (glpk) returned non-zero return code

### ISSUE THREAD

**Issue by felixfan** [FRED-2/OptiType#2]
0 packages
---------------

```
biopython==1.64
Coopr 3.5.8787 (CPython 2.7.6 on Linux 3.13.0-37-generic)
matplotlib==1.3.1
pandas==0.13.1
solver: glpk 4.35
```

1 run the example command on Ubuntu 14.04 LTS
------------

```
python OptiTypePipeline.py -i ./test/exome/NA11995_SRR766010_1_fished.fastq ./test/exome/NA11995_SRR766010_2_fished.fastq -d -v -o ./test/exome/
```

2 Warnings and Errors:
-----------------------------

```
WARNING: No construction rule or expression specified for constraint 'c'     
Invalid option `--threads'; try /usr/local/bin/glpsol --help    
ERROR: "[base]/dist-packages/coopr/opt/base/solvers.py", 448, solve     
	Solver (glpk) returned non-zero return code (1)   
ERROR: "[base]/dist-packages/coopr/opt/base/solvers.py", 451, solve   
	See the solver log above for diagnostic information.    
glp_read_lp: reading problem data from `/tmp/tmpA9lW95.pyomo.lp'...   
/tmp/tmpA9lW95.pyomo.lp:3620: warning: lower bound of variable `x481' redefined    
/tmp/tmpA9lW95.pyomo.lp:3620: warning: upper bound of variable `x481' redefined    
...   (multiple lines similar warnings)
```

3 Results
---------------------

```
	A1	A2	B1	B2	C1	C2	Reads	Objective
0	A*01:01	A*01:01	B*08:01	B*57:01	C*07:01	C*06:02	1156	1135.192
```

**Comment by MarisaMatey** [comment]
I've changed THREADS = 1 and I am still getting this error. And I get no output, Optitype crashes before.

Thanks

**Comment by b-schubert** [comment]
Could you please add your trace back, the version of the python modules, which solver you are using, and your configuration file. Otherwise it is hard for us to check whats going on. Also are you using a resent pull of the git repository?

Best,
Benni

**Comment by MarisaMatey** [comment]
Trace Back:

Traceback (most recent call last):
  File "OptiTypePipeline.py", line 309, in <module>
    result = op.solve(args.enumerate)
  File "/net/home/home/projectsa/pr_46455/apps/OptiType/model.py", line
154, in solve
    del self.__solver.options["threads"]
KeyError: 'threads'

The python version in 2.7, the solver is cbc, and here is the config.ini
file

[MAPPING]
#please specify the razerS3 binary path
RAZERS3=/...omitted.../razers3
THREADS=1

[LIBRARIES]
RNA_REF=./data/hla_reference_rna.fasta
DNA_REF=./data/hla_reference_dna.fasta
ALLELES=./data/alleles.h5

[OPTIMIZATION]
#the solver has to be supported by Coopr
#SOLVER=glpk
SOLVER=/...omitted.../cbc
THREADS=1


On 31 August 2015 at 12:39, b-schubert <notifications@github.com> wrote:

> Could you please add your trace back, the version of the python modules,
> which solver you are using, and your configuration file. Otherwise it is
> hard for us to check whats going on. Also are you using a resent pull of
> the git repository?
>
> Best,
> Benni
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FRED-2/OptiType/issues/2#issuecomment-136329760>.
>



-- 
María Luisa Matey Hernández
(+45) 50197809
Tåsingegade 29, 243
2100, København Ø
Danmark

**Comment by b-schubert** [comment]
Is that the complete traceback?

The only thing that is incorrectly configured is the  solver entry. You only have to specify the solver name without the path. But the solver has to be globally executable (i.e. if you type cbc in your terminal it should call it). Pyomo is handling the command line calls and communication with CBC.

If that doesn't solve it, could you please specify the version of pyomo, and what input files you are using. Are you using the test inputs? If not, is this error also occurring when using the test inputs?

**Comment by b-schubert** [comment]
Is the problem resolved now?

**Comment by caqyflichking** [comment]
Same issue. Solved by "sudo ldconfig " after "sudo make install"
