### ISSUE TITLE
Can I use already mapped and SNP calling VCF to do OptiType?

### ISSUE THREAD

**Issue by cenielyj** [FRED-2/OptiType#21]
This is Yijia Li from Yunnan Province Stem Cell Bank, China.
We are very interested using your OptiType to do HLA typing.
However may I ask if I can use already mapped and SNP calling VCF to do that without using the original fastq file?
Thanks very much.

**Comment by andras86** [comment]
Dear Yijia,
It's not possible with OptiType. I suggest you look into HLA*IMP:02, SNP2HLA or HIBAG, but beware the limitations of resolving HLA genotypes from SNP data alone.
