### ISSUE TITLE
Error message for too few reads

### ISSUE THREAD

**Issue by alvinwt** [FRED-2/OptiType#25]
Hi, I have been getting 

````
Traceback (most recent call last):
  File "/data/rozencompute2/a0073895/optitest/OptiType/OptiTypePipeline.py", line 304, in <module>
    "in your config file (currently %.3f), because you may need to resort to using unpaired reads.") % unpaired_weight
TypeError: not enough arguments for format string
````

even when I have changed the unpaired weights in the config.ini file to 1. I am wondering if this is a error message when there are few reads in the input fastq or if something else is happening.

**Comment by andras86** [comment]
It should still run through, it was just an unescaped percentage sign in a string substitution one line above, fixed now. BTW, why do you have so many unpairable reads? Could you run this with deletebam=false in the config file and e-mail me the intermediate bam files and the coverage plot? I've never come across a sample like this (which is the reason that unescaped % went unnoticed for so long :))

**Comment by andras86** [comment]
And forgot to answer your question: you get this warning if your HLA reads' individual ends can't be paired up consistently (i.e. both ends mapping to at least one common allele) for more than 10% of them. I could only see this happen for very long insert sizes where one end always falls in the exon2-exon3 reference window but the other is always left out.

**Comment by alvinwt** [comment]
hi @andras86, I fixed the unescaped % and found a bug in my code. The pre-filtering step was not done correctly and generated a lot of unpaired reads. Btw, I ran Optitype on a whole bunch of samples and you might be interested. Let's take this offline.
