### ISSUE TITLE
Some problem about RazerS 3.1

### ISSUE THREAD

**Issue by WeijianYe** [FRED-2/OptiType#3]
Hi,
    When I installed the OptiType, I found that the website about Razer3 could not be accessed and it seems that there is no other way to download the Razer3. Could you mind to help?

**Comment by yeemanchan** [comment]
I have the same problem too. I think the issue is glpsol doesn't support "-s" option.

I want to try CBC too but unfortunately their site is down as of now...

**Comment by b-schubert** [comment]
The project site is up.  I changed the Installation guide to CBC now. I couldn't find any mentions of that bug in coopr related forums.

**Comment by yeemanchan** [comment]
CBC works for me. 

But it will be great if it also supports glpsol from glpk-4.55. Or tell us which version of glpk it supports.

**Comment by b-schubert** [comment]
As I said, I couldn't reproduce the problem. I tried several GLPK versions (from 4.50 to 4.55) and all worked fine for me. I contacted the Coopr developers asking for help. But so far haven't got an answer.

I'll keep trying to solve this issue.

Do you guys have any problems calling glpk from command line with a toy problem?

**Comment by yeemanchan** [comment]
So who is passing the "-s" option to glpsol? Is it OptiType or Coorp?

**Comment by b-schubert** [comment]
So I got an answer. 

Could you please name the solver 'glpk' instead 'glpsol' in the config file. This should fix your problems hopefully.

Here is the quote from Gabriel Hackebeil:

>I can reproduce this error when I use GLPK through the NL file interface, which GLPK does not >support. However, it is very likely that this is unintentional and coming about by your software (or >users) choosing “glpsol” as the solver name rather than “glpk”. We have a registered solver plugins >that recognizes the solver name “glpk”, which launches the necessary interface to the “glpsol” >executable. When no registered solver plugins match a given name (e.g., “glpsol”), we fall back on >using the NL file interface because it is a generic interface to a large number of different solvers.
>
>Short answer:
>
>(incorrect)
>--solver=glpsol
>(correct)
>--solver=glpk

(incorrect)
SolverFactory('glpsol’)
(correct)
SolverFactory(‘glpk’)

Gabe

**Comment by yeemanchan** [comment]
I renamed the executable and also changed config.ini but it seems like it is assuming glpsol. 

----------------------------
user@HPC:/tank/optitype$ time python OptiTypePipeline.py -i SRR1558164_fished_1.fastq SRR1558164_fished_2.fastq --dna -o ./SRR1558164/
/usr/local/lib/python2.7/dist-packages/pandas/util/decorators.py:13: FutureWarning: diff is deprecated. Use difference instead
  FutureWarning)
WARNING: No construction rule or expression specified for constraint 'c'
WARNING: "[base]/dist-packages/coopr/solvers/plugins/solvers/GLPK_old.py", 69, executable
	Could not locate the 'glpsol' executable, which is required for solver 'glpk'
WARNING: Solver does not support multi-threading. Please change the config file accordingly! Fall back to single-threading.
Traceback (most recent call last):
  File "OptiTypePipeline.py", line 309, in <module>
    result = op.solve(args.enumerate)
  File "/tank/optitype/model.py", line 154, in solve
    del self.__solver.options["threads"]
KeyError: 'threads'

**Comment by b-schubert** [comment]
you dont need to rename the executable, just rename the parameter in the config file from:

solver=glpsol

to

solver=glpk

that should invoke cooprs GLPKs interfaces instead of a generic interface (which happens when naming it glpsol)

Also, you should check whether glpk is still globally executable by typing the following in your command line:
glpsol --help

If the help pops up, everything should be fine and OptiType should be working.

**Comment by yeemanchan** [comment]
Finally, I make glpk works. You have to set the solver in config.ini to "glpk" even if the executable is called "glpsol"

Thanks for your follow up.
