### ISSUE TITLE
Memory issues with Razers3

### ISSUE THREAD

**Issue by alexanderwhatley** [FRED-2/OptiType#44]
I have a 28GB bam file, and I'm running into memory issues with Razers3 even when I allocate 32GB of RAM for this job. Do you have any recommendations on what to do? Thanks.

**Comment by andras86** [comment]
Is this the intermediate bam file produced by OptiType, or you're trying to give OT a bam file (reads mapped against full reference genome) as input?

**Comment by alexanderwhatley** [comment]
I fixed this problem by breaking up the BAM file to only include chromosome 6 data.
