### ISSUE TITLE
Pyomo-supported ILP solver

### ISSUE THREAD

**Issue by riyuebao** [FRED-2/OptiType#48]
Hello,

OptiType returned the following message while calling the module `model.py`: 

```bash
Invalid option '-s'; try /group/bioinformatics/software/GLPK/4.61/bin/glpsol --help
ERROR: "[base]/site-packages/pyomo/opt/base/solvers.py", 599, solve
	Solver (asl) returned non-zero return code (1)
ERROR: "[base]/site-packages/pyomo/opt/base/solvers.py", 602, solve
	See the solver log above for diagnostic information.
```

This is my command:

```bash
module load anaconda3
source activate python2.7

module load GLPK/4.61 HDF5/1.10.0-patch1 samtools/1.2 bwa/0.7.15 sambamba/0.5.6

python ./OptiTypePipeline.py -i ./test/exome/NA11995_SRR766010_1_fished.fastq ./test/exome/NA11995_SRR766010_2_fished.fastq -o test -d -v

source deactivate
```

I was not able to install `RazerS` and `CPLEX` on our server, hence went for `bwa` and `GLPK` instead. I modified `OptiTypePipeline.py` a little bit to take in `bwa` alignment commands instead of the default `RazerS` .

The command-line solver for `GLPK` is `glpsol`, which I also changed in `config.ini`. Could that be the reason why the error was reported? The modified `OptiTypePipeline.py`, config, commands and log files are attached here if helpful [myfiles.zip](https://github.com/FRED-2/OptiType/files/925053/myfiles.zip)

Any help would be highly appreciated. Thanks much in advance :)

Best,
Riyue (Sunny)
The University of Chicago

**Comment by b-schubert** [comment]
Hi Riyue,

Could you change the solver name to ```glpk```and try it again. Also make sure that glpk and bwa can be found in PATH.

I'm also not sure that bwa is a good alternative as OptiType needs an ```all-best```mapping approach.

If you have problems with installing the requirements by hand, you could try out our Docker image which comes with a pre-configured RazerS3 and a ILP solver (see installation instruction for more infos).

**Comment by riyuebao** [comment]
Hi Benjamin,

Thanks for the quick response! I created a symbolic link `glpk -> glpsol` and it worked. Yay!! 

Here is the result from running the test exome fastq files and the coverage plot 
[2017_04_17_13_27_05_coverage_plot.pdf](https://github.com/FRED-2/OptiType/files/926347/2017_04_17_13_27_05_coverage_plot.pdf)

```bash 
	A1	A2	B1	B2	C1	C2	Reads	Objective
0	A*24:03	A*24:03	B*08:12	B*57:03			31.0	29.844
```

I agree `bwa` may not be a good alternative for `razers3`. `Docker` would be an excellent option but unfortunately our server does not have it installed. Would you have any recommendations on other aligners for `OptiType`, e. g. `bowtie2` or `novoalign`? `bowtie2` has the alignment mode `-a mode: search for and report all alignments` and `novoalign` has `-r all`. Would these be potential good alternatives? Thanks much in advance!

Best,
Riyue

**Comment by b-schubert** [comment]
Uh, the result is definitely incorrect. This is probably due to bwa. You could try Yara (page currently down - https://www.seqan.de/yara/), which is the successor of RazerS3 and should be natively supported by OptiType.

What exactly went wrong during RazerS3's installation?

**Comment by riyuebao** [comment]
Thanks Benjamin. Yup that was due to the default alignment settings of `bwa`, which does not report all best alignments and filter out multitargets, and is not suitable for mapping to HLA loci.

The issue with RazerS3's installation was the `gcc` version - but our system adm helped fix it yesterday!! :) I compiled `yara` and `razers3` and they both worked (BTW if anyone is interested in compiling individual tools from `seqan`, the installation instructions on `yara` [github](https://github.com/bede/yara) is super helpful). 

This is the new result generated with aligner `razers3`:
dna fastq files & `-d`: [2017_04_19_12_50_43_coverage_plot.pdf](https://github.com/FRED-2/OptiType/files/936870/2017_04_19_12_50_43_coverage_plot.pdf)
```bash
	A1	A2	B1	B2	C1	C2	Reads	Objective
0	A*01:01	A*01:01	B*08:01	B*57:01	C*07:01	C*06:02	1156.0	1135.192
```
rna fastq files & `-r`: [2017_04_19_12_53_22_coverage_plot.pdf](https://github.com/FRED-2/OptiType/files/936933/2017_04_19_12_53_22_coverage_plot.pdf)
```bash
	A1	A2	B1	B2	C1	C2	Reads	Objective
0	A*31:01	A*68:01	B*40:01	B*51:01	C*15:02	C*03:04	132.0	128.436
```

The results make a lot more sense now ... :)

**Comment by riyuebao** [comment]
Hi just want to follow up that I have run all my samples by `OptiType` and the results look great. For each exome it took 5 to 15 mins to run with 8 threads from raw fastq to final output - super fast!
