### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'LIBRARIES'

### ISSUE THREAD

**Issue by jungminchoi** [FRED-2/OptiType#6]
Hello,

I ran the script with the provided exome test files and got these error messages. I would greatly appreciate it if you can have a look and help me troubleshoot the issues.

    [jc2545@login-0-1 exome]$ python ~/programs/OptiType-master/OptiTypePipeline.py -i NA11995_SRR766010_1_fished.fastq NA11995_SRR766010_2_fished.fastq -d -v -o .
    Traceback (most recent call last):
      File "/home/jc2545/programs/OptiType-master/OptiTypePipeline.py", line 195, in <module>
    ALLELE_HDF = config.get("LIBRARIES", "ALLELES")
      File "/home/jc2545/python/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
    ConfigParser.NoSectionError: No section: 'LIBRARIES'

Here is my config.ini file

    [jc2545@login-0-0 OptiType-master]$ cat config.ini 
    [MAPPING]
    #please specify the razerS3 binary path
    RAZERS3=/home/jc2545/programs/razers3-3.4.0-Linux-x86_64/bin/razers3
    THREADS=8

    [LIBRARIES]
    RNA_REF=./data/hla_reference_rna.fasta
    DNA_REF=./data/hla_reference_dna.fasta
    ALLELES=./data/alleles.h5

    [OPTIMIZATION]
    #the solver has to be supported by Coopr
    SOLVER=cbc
    THREADS=1

I believe all the required softwares and libraries are installed.

    [jc2545@login-0-1 exome]$ python ~/programs/OptiType-master/OptiTypePipeline.py --help
    usage: OptiType [-h] --input INPUT [INPUT ...] (--rna | --dna) [--beta BETA]
                [--enumerate ENUMERATE] --outdir OUTDIR [--verbose]

    OptiType: 4-digit HLA typer

    optional arguments:
      -h, --help            show this help message and exit
      --input INPUT [INPUT ...], -i INPUT [INPUT ...]
                            Fastq files with fished HLA reads. Max two files (for
                            paired-end)
      --rna, -r             Specifiying the mapped data as RNA.
      --dna, -d             Specifiying the mapped data as DNA.
      --beta BETA, -b BETA  The beta value for for homozygosity detection.
      --enumerate ENUMERATE, -e ENUMERATE
                             The number of enumerations.
      --outdir OUTDIR, -o OUTDIR
                            Specifies the out directory to which all files should
                            be written
      --verbose, -v         Set verbose mode on.

**Comment by b-schubert** [comment]
Hi,

We are using relative paths within OptiType. You either have to call OptiType within ~/programs/OptiType-master/ or you have to change all relative paths to absolute paths within the config.ini and OptiTypePipeline.py.

That should resolve the exception.

Best,
Benni

**Comment by jungminchoi** [comment]
Hi Benni,

Thank so much for your prompt solution.

Best,
Jungmin
