### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by JunhuiLi1017** [FRED-2/OptiType#67]
OptiType was installed with `conda install optitype` , and it can print help message, but cannot deal with small data( HLA_1.fastq = 31k and HLA1_2.fastq = 31k).
The command is `python OptiTypePipeline.py --input HLA1_1.fastq HLA1_2.fastq --rna -v -o ./test/rna/`
and error information is as follows:

mapping with 4 threads...
 0:00:04.45 Mapping HLA1_1.fastq to NUC reference...
 0:00:10.85 Mapping HLA1_2.fastq to NUC reference...
Segmentation fault (core dumped)

how can I deal with this? thanks

**Comment by b-schubert** [comment]
Unfortunately, we are not maintaining the conda container. Could you perhaps try and install OptiType directly on your system or use our Docker container and see if the error persists?

**Comment by onJSnow** [comment]
@b-schubert  Thanks a lot，I will try to install OptiType directly (Docker can not be installed on my system, CentOS release 6.3).
