### ISSUE TITLE
Starting with bam files

### ISSUE THREAD

**Issue by toddcreasy75** [FRED-2/OptiType#72]
Hi, 

Is there anyway for OptiType to take bam files directly without having to run bam2fq?

Thanks,

-todd

**Comment by andras86** [comment]
Hi Todd,

I suppose you mean bam files mapped against hg38. No, the reads need to be extracted first, at least from the HLA regions on chromosome 6, approximately megabases 29.5-33.2. Depending on what mapper you used, the unmapped reads might be needed too (although bwa mem defaults work well enough that HLA reads almost never stay unmapped). But assuming your bam file is indexed, as they usually are, it's a very fast operation with samtools view + samtools bam2fq.

**Comment by toddcreasy75** [comment]
Thanks for the helpful info.
