### ISSUE TITLE
Using Optitype on Mouse Data

### ISSUE THREAD

**Issue by jplaverdure** [FRED-2/OptiType#76]
Hello,

I realise this is not an "issue" per se, but could any of you guide me in the steps necessary for running optitype on mouse RNASeq data ?
I realise I would at least need to compile a fasta file corresponding to the mouse HLA allele sequences but what about the resolver ? Is it currently hard-coded towards the provided HLA sequences provided here ?

Thank you !

**Comment by andras86** [comment]
Hi Jean-Philippe,

Yeah, plenty of pieces are hard-coded, and it's not a trivial port, but if you feel adventurous you can try tweaking it, and I can give you some pointers. Write me an e-mail.

Best,
Andras

**Comment by NikdAK** [comment]
Hi,
I would also be interested in using OptiType for mouse WES data. 
Did you provide him some information via email, which you could now also post here?

My first struggle now is the .h5 file. 

Thanks!
