### ISSUE TITLE
Keeping bam

### ISSUE THREAD

**Issue by ktroule** [FRED-2/OptiType#77]
I'm running Optitype in docker. Is there any way to keep the aligned bam to reference HLA fasta? I think its created as intermediate file, and I would like to keep it.

Not sure how to modify the config file that is in the docker image.

Thanks

**Comment by ktroule** [comment]
Thanks for the fast answer!

**Comment by ktroule** [comment]
I'm trying to get into the image to modify the config file in the image and then save it into a new image but I'm unable to do it. We've tried it different ways.

`docker run -i -t fred2/optitype:latest /bin/bash`

`usage: OptiType [-h] --input FQ [FQ ...] (--rna | --dna) [--beta B]
                [--enumerate N] --outdir OUTDIR [--prefix PREFIX] [--verbose]
                [--config CONFIG]
OptiType: error: argument --input/-i is required`

Thanks

**Comment by ktroule** [comment]
Finally solved

`docker run -it --entrypoint /bin/bash fred2/optitype:latest`

**Comment by ktroule** [comment]
Yet another problem. Once inside I cannot modify the config.ini as I have no privileges to `install apt-get install nano` or other text reading tool.  We the users have no way to do this as we have no control over the biodocker user.

Anyhow to modify this file?

**Comment by ktroule** [comment]
Finally managed to get into the image, modify the config.ini folder, but after commit it wont work (it does not print the usage parameters of the program).

**Comment by b-schubert** [comment]
@ktroule You don't have to manipulate the docker image at all. Just use the -c command to specify your modified config file (with the docker internal paths i.e. /data/modified_config.yml) and that should to the trick.

**Comment by ktroule** [comment]
Thanks it's finally working.
