### ISSUE TITLE
OptiType result output

### ISSUE THREAD

**Issue by ShahiRB** [FRED-2/OptiType#85]
Hi, 
Why I don't get HLA typing of all the genes (A, B and C) in a single run?  Rather, I have to run multiple times to get that (as shown below). I wonder if its bug.

And, do you think removing duplicate reads from input files (.bam) is wise before running OptiType ?

=> 2018_11_29_11_19_21/2018_11_29_11_19_21_result.tsv <==
        A1      A2      B1      B2      C1      C2      Reads   Objective
	A*03:01 A*25:01                                 293.0   290.363
Run2
==> 2018_11_29_11_19_41/2018_11_29_11_19_41_result.tsv <==
        A1      A2      B1      B2      C1      C2      Reads   Objective
	A*25:01 A*03:01                 C*06:02 C*12:03 330.0   324.05999999999995
Run3
==> 2018_11_29_11_20_01/2018_11_29_11_20_01_result.tsv <==
        A1      A2      B1      B2      C1      C2      Reads   Objective
	A*03:01 A*25:01                                 293.0   290.363
Run4
==> 2018_11_29_11_20_21/2018_11_29_11_20_21_result.tsv <==
        A1      A2      B1      B2      C1      C2      Reads   Objective
	A*25:01 A*03:01 B*15:50 B*15:50                 295.0   292.33500000000004

Regards,
Rajendra

**Comment by andras86** [comment]
That's one weird bug... I cannot fathom what could cause this. Can you turn on deletebam=false in the config file, and e-mail me to them from two runs that produced different results?

**Comment by biotechnepal** [comment]
I used these commands.
1] razers3 -i 95 -m 1 -dr 0 -o sample.bam --thread-count 12 /work/user/databases/OptiType_data_and_config_1.3.2/hla_reference_dna.fasta sample.fq
2] OptiTypePipeline.py  --dna   -i sample_r1.bam  sample_r2.bam -o /work/user/ -e 1

But I got this warning regarding pd.DataFrame(below). Do you think it may have caused the problem?

/theia/home/apps/CO7/magnycours-ib/software/OptiType/1.3.2-foss-2018b-Python-3.6.6/hlatyper.py:239: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  pos_df = pd.DataFrame.from_items(iter(hits.items())).T
/apps/brussel/CO7/magnycours-ib/software/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/series.py:851: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]

**Comment by andras86** [comment]
It could be related. In any case I'd like to try to reproduce it. Can you e-mail them?

**Comment by yujijun** [comment]
Hi, asdras86. I also don't get HLA typing of all the genes (A, B and C) in a single run, Is there any of solution for this problem?
thanks.

**Comment by koujiaodahan** [comment]
Hi,My output format is not the four digit.... ,and i dont find any error,why??my output is : 
    A1  A2  B1  B2  C1  C2  Reads   Objective
0   HLA00074_HLA00073   HLA00097    HLA00293    HLA00368    HLA01711_HLA00420   HLA00445    276.0   261.07599999999996

**Comment by andras86** [comment]
@koujiaodahan Are you sure the OptiType version you ran is from this github repository? I know some people tweaked OptiType to output the IMGT identifier, but it doesn't do it by default and never did.
